### ISSUE TITLE
Add netlify preview build to PR

### ISSUE THREAD

**Issue by Pradhvan** [scanapi/website#13]
It would be great if we could add a Netlify build[0] every time someone creates a PR. That way changes in the PR can be directly deployed to netlify URL and once the PR is merged the URL is no longer accessible.  Making it a bit easier for the reviewer to see the changes before he/she/they dive into the codebase.  

![image](https://user-images.githubusercontent.com/13925830/88571182-db1d8380-d05a-11ea-8fe1-a16bdf4cd315.png)

[0] https://docs.netlify.com/configure-builds/get-started/#basic-build-settings

**Comment by Pradhvan** [comment]
I would be happy to take this up 😄

**Comment by camilamaia** [comment]
@Pradhvan this is a really good idea! But first we need to migrate from GitHub Pages to Netlifly. I created a issue for it: https://github.com/scanapi/website/issues/14

**Comment by barbosa** [comment]
@Pradhvan it ended up being just a simple configuration on Netlify.

Here's the preview: https://github.com/scanapi/website/pull/32

Will close this. Thank you for bringing this up!
