### ISSUE TITLE
Add Previous and Next Page to Tutorial Layout

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#17]
## Add Previous and Next Page to Tutorial Layout

To make it possible to navigate between the tutorials pages. Something like this:

![image](https://user-images.githubusercontent.com/2728804/89351298-1dad1480-d688-11ea-8df3-cf317dab24a3.png)

[Django's Doc](https://docs.djangoproject.com/en/3.1/contents/) (see the bottom of the page, right on top of the footer)

Here is the template where we should add the navigation:
https://github.com/scanapi/website/blob/master/_layouts/tutorial.html

We are current not showing any tutorial in the website because we don't have the content yet. But we already have the template, which is the link above. Also, we have some fake pages if testing is needed:

https://github.com/scanapi/website/tree/master/_tutorials

The idea is to have arrows to navigate to the next and the previous page. For example:

Page 1:
- `>` Arrow with page 2's title and link to page 2

Page 2: 
- `<` Arrow with page 1's title and link to page 1
- `>` Arrow with page 3's title and link to page 3

Page 3:
- `<` Arrow with page 1's title and link to page 2
- `>` Arrow with page 3's title and link to page 4

...

Last Page:
- `<` Arrow with previous page's title and link to the previous page

**Comment by ShubhamSood1406** [comment]
Where to add this functionality and can you tell more about this.

**Comment by camilamaia** [comment]
@ShubhamSood1406 I've updated the description of the issue. Can you tell me if it is clear now? Thanks!

**Comment by ShubhamSood1406** [comment]
Can you tell where(on which page) to add these navigation layouts?

**Comment by camilamaia** [comment]
@ShubhamSood1406 it should be added to this layout after this line: https://github.com/scanapi/website/blob/master/_layouts/tutorial.html#L15

It should get dynamically the navigation information via the `page` object. Something like `page.next_title`, `page.next_link`, `page.previous_link`, `page.previous_title`.
