### ISSUE TITLE
Update Documentation with new command `scanapi run`

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#19]
## Update Documentation with new command `scanapi run`

Before for running ScanAPI the command was:

```bash
$ scanapi <spec_path>
```

Now it is:

```bash
$ scanapi run <spec_path>
```

Documentation should reflect this change.

https://github.com/scanapi/scanapi/issues/226

**Comment by Pradhvan** [comment]
@camilamaia this seems like a quick fix. I can pick this up, if no one is working on it. 😄
