### ISSUE TITLE
Add a link to ScanAPI Visual Studio Code Extension

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#34]
## Add a link to ScanAPI Visual Studio Code Extension

We have a Visual Studio Code Extension for ScanAPI. It would be nice to have a link to it on our website:
https://marketplace.visualstudio.com/items?itemName=ScanAPI.scanapi

![image](https://user-images.githubusercontent.com/2728804/94600427-3bea5780-0268-11eb-8116-5a2c07e9fd02.png)

**Comment by ShubhamSood1406** [comment]
I can do this, but tell where to add that link and what should be the name of that link.

**Comment by camilamaia** [comment]
@ShubhamSood1406 I've assigned you! I've also updated the issue description with the menu and the name of it for the link.

**Comment by camilamaia** [comment]
Closed by #40
