### ISSUE TITLE
Add a link to ScanAPI GitHub Action

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#35]
## Add a link to ScanAPI GitHub Action

We have a GitHub action for ScanAPI. It would be nice to have a link to it on our website:
https://github.com/marketplace/actions/scanapi

**Comment by ShubhamSood1406** [comment]
Can I work on it, can you explain what to do and where is the website link?

**Comment by camilamaia** [comment]
@ShubhamSood1406 yes, for sure! You can access the website at: https://scanapi.dev and [this](https://github.com/scanapi/website) is the repo.

I believe we could have the link for the GitHub Action here in the menu, after `examples`
![image](https://user-images.githubusercontent.com/2728804/94573858-ddfa4780-0248-11eb-8681-caafcd74a470.png)

This is the link for the github action https://github.com/marketplace/actions/scanapi

**Comment by ShubhamSood1406** [comment]
Should I ScanAPI as a heading or anything else?

**Comment by ShubhamSood1406** [comment]
@camilamaia You assigned this issue to @Pradhvan, but shouldn't it be assigned to me?

**Comment by camilamaia** [comment]
@ShubhamSood1406 Sorry, I've just fixed the assignee.

![image](https://user-images.githubusercontent.com/2728804/94600340-22e1a680-0268-11eb-9d04-4ec96511df3c.png)

**Comment by camilamaia** [comment]
Closed by #40

**Comment by ShubhamSood1406** [comment]
> Closed by #40

@camilamaia  Can you add `hacktoberfest` topics is your repository so that this repo will be eligible for Hacktoberfest. Due to updates in Hacktoberfest policies.

**Comment by camilamaia** [comment]
> > Closed by #40
> 
> @camilamaia Can you add `hacktoberfest` topics is your repository so that this repo will be eligible for Hacktoberfest. Due to updates in Hacktoberfest policies.

Done!
