### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#36]
Fix broken link to `Custom Variables` at https://scanapi.dev/docs_v1/specification/basic_structure.html#vars
![image](https://user-images.githubusercontent.com/2728804/93769557-592c7f80-fbf1-11ea-8d03-b64aa42c828c.png)

Current, the link is pointing to https://scanapi.dev/docs_v1/specification/basic_structure.html#todo

But, the link **should** point to: https://scanapi.dev/docs_v1/specification/custom_variables.html

**Comment by ShubhamSood1406** [comment]
Can I do this?

**Comment by camilamaia** [comment]
@ShubhamSood1406 sure! I've updated the issue description and assigned you, thanks! Please, let me know if you have any questions.

**Comment by ShubhamSood1406** [comment]
@camilamaia Thank you, I will PR it during Hacktoberfest.

**Comment by camilamaia** [comment]
Closed by #40
