### ISSUE TITLE
Stop using `gh-pages` gem and upgrade to jekyll 4.x

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#39]
# Stop using `gh-pages` gem and Upgrade to jekyll 4.x

We are using Netlify to deploy the website instead of GitHub Pages now. For this reason, we can start using jekyll 4.x gem directly instead of `gh-pages` gem.

https://github.com/scanapi/website/blob/master/Gemfile#L7

**Comment by beatorizu** [comment]
Hey, I would like to try this issue, but I do not know ruby

**Comment by camilamaia** [comment]
Hey @beatorizu thanks for the comment! For this one we need to understand how [RubyGems](https://guides.rubygems.org/rubygems-basics/) works (it is similar to python pip!) and how [Jekyll](http://jekyllrb.com/) works.

We need to:
- First, [uninstall](https://guides.rubygems.org/rubygems-basics/#uninstalling-gems) gh-pages gem
- Then [install](https://guides.rubygems.org/rubygems-basics/#installing-gems) jekyll gem version 4.x
- And finally, adapt the code to match with the new Jekyll version - if needed: https://jekyllrb.com/docs/upgrading/3-to-4/.

We also have more pure python issues [here](https://github.com/scanapi/scanapi/issues), if you prefer (I saw in your github that you are a Python developer).

Let me know if you still want to work on this.

**Comment by beatorizu** [comment]
I could try the [#316](https://github.com/scanapi/scanapi/issues/316) or [#303](https://github.com/scanapi/scanapi/issues/303) or [#261](https://github.com/scanapi/scanapi/issues/261) :grin:

**Comment by camilamaia** [comment]
@beatorizu I believe [#261](https://github.com/scanapi/scanapi/issues/261) is a good one to start with!
