### ISSUE TITLE
Sandwich menu

### ISSUE THREAD

**Issue by camilamaia** [scanapi/website#55]
## Sandwich menu

To avoid breaking menu on mobile:

![image](https://user-images.githubusercontent.com/2728804/105523065-b7ab5c80-5cbc-11eb-9cc2-fe6486a52b35.png)

![image](https://user-images.githubusercontent.com/2728804/105522934-9a768e00-5cbc-11eb-86d4-a9596b943e12.png)

**Comment by ShubhamSood1406** [comment]
Can I work on this?

**Comment by camilamaia** [comment]
Yes, sure thing @ShubhamSood1406 !

**Comment by ShubhamSood1406** [comment]
Do you want all things in the Navigation Bar (including Twitter & Github Icon)?

**Comment by camilamaia** [comment]
> Do you want all things in the Navigation Bar (including Twitter & Github Icon)?

Hmmm, great question. What do you think is better?

@astenstrasser @marcuxyz any thoughts here? Do you think Twitter and Github Icon should be in the sandwich menu too? If yes, should they be text or icons?
