### ISSUE TITLE
Tests Summary Image not being show correctly in examples

### ISSUE THREAD

**Issue by kurianbenoy** [scanapi/website#90]
In Tutorial, the test summary of scanapi is not being shown correctly in Images. The test summary should be shown at the top instead of being shown at the bottom.

![image](https://user-images.githubusercontent.com/24592806/133999438-06f80871-c7ce-483e-b96b-300950e8891c.png)

When the API is actually at the top.

![image](https://user-images.githubusercontent.com/24592806/134000251-42844e4b-30e6-42cb-b136-81344018ff91.png)

**Comment by Pradhvan** [comment]
@kurianbenoy nice catch. Looks like we forgot to update the documentation when we made a new release. Would you be interested in taking this up ?
